### ISSUE TITLE
Production deployment checklist

### ISSUE THREAD

**Issue by ferric-sol** [ferric-sol/dcbot-grammy#1]
## Pre-deploy
- [x] Rename bot - @austintgriffith
- [ ] Fund faucet with SALT and xDAI - @austintgriffith
- [ ] Create new github project 
- [x] Create new telegram bot
- [x] Setup new telegram bot commands

## Rotate Keys
- [x] GNOSIS_API_KEY
- [x] FRUITBOT_FAUCET_KEY
- [x] TELEGRAM_API_KEY

## Deploy
- [ ] Create new vercel project
- [x] Attach it to new KV store

## Post-deploy
- [x] Test bot to make sure all commands work
